site_name: 'Tinkoff Invest API Documentation'
docs_dir: docs
theme:
  name: material
  language: 'ru'
  palette:
    primary: black
    accent: yellow
  # custom_dir: swagger-iu/

nav:
- Начало работы: index.md
- Авторизация: auth.md
- Окружения: env.md
- "Протокол: rest": rest.md
- "Протокол: streaming": marketdata.md
- FAQ: faq.md
